import type { PlaceSummary } from './types'

export const MAP_INITIAL_CENTER = {
  latitude: 37.558721,
  longitude: 126.92444,
} as const

export const MOCK_PLACES: PlaceSummary[] = [
  {
    id: 'place-restaurant-1',
    naver_place_id: '10001',
    naver_place_url: 'https://map.naver.com/p/entry/place/10001',
    name: '누리 식당',
    road_address: '서울 마포구 양화로19길 22-16 1층',
    latitude: 37.55918,
    longitude: 126.92374,
    place_type: 'restaurant',
    zeropay_status: 'available',
    average_rating: 4.7,
    review_count: 12,
    added_by_name: '김누리',
    recommendation_count: 9,
    my_recommendation_active: true,
    my_review: {
      id: 'review-mine-1',
      author_name: '내 리뷰',
      content: '점심 모임으로 가기 좋은 식당이에요.',
      created_at: '2026-03-07',
      rating_score: 5,
    },
    reviews: [
      {
        id: 'review-1',
        author_name: '김누리',
        content: '점심 모임으로 가기 좋은 식당이에요.',
        created_at: '2026-03-07',
        rating_score: 5,
      },
      {
        id: 'review-2',
        author_name: '박지도',
        content: '',
        created_at: '2026-03-05',
        rating_score: 4,
      },
    ],
  },
  {
    id: 'place-cafe-1',
    naver_place_id: '10002',
    naver_place_url: 'https://map.naver.com/p/entry/place/10002',
    name: '양화로 카페',
    road_address: '서울 마포구 양화로19길 20 2층',
    latitude: 37.55831,
    longitude: 126.92518,
    place_type: 'cafe',
    zeropay_status: 'needs_verification',
    average_rating: 4.3,
    review_count: 8,
    added_by_name: '이합정',
    recommendation_count: 5,
    my_recommendation_active: false,
    my_review: null,
    reviews: [
      {
        id: 'review-3',
        author_name: '이합정',
        content: '노트북 작업하기 좋고 조용해요.',
        created_at: '2026-03-06',
        rating_score: 4,
      },
      {
        id: 'review-4',
        author_name: '최카페',
        content: '오후 시간대에도 자리 여유가 있는 편입니다.',
        created_at: '2026-03-04',
        rating_score: 5,
      },
    ],
  },
  {
    id: 'place-restaurant-2',
    naver_place_id: '10003',
    naver_place_url: 'https://map.naver.com/p/entry/place/10003',
    name: '합정 점심집',
    road_address: '서울 마포구 양화로17길 15',
    latitude: 37.55794,
    longitude: 126.92488,
    place_type: 'restaurant',
    zeropay_status: 'unavailable',
    average_rating: 4.1,
    review_count: 5,
    added_by_name: '정점심',
    recommendation_count: 2,
    my_recommendation_active: false,
    my_review: null,
    reviews: [
      {
        id: 'review-5',
        author_name: '정점심',
        content: '무난하게 점심 먹기 좋아요.',
        created_at: '2026-03-03',
        rating_score: 4,
      },
    ],
  },
  {
    id: 'place-no-coord',
    naver_place_id: '10004',
    naver_place_url: 'https://map.naver.com/p/entry/place/10004',
    name: '좌표 없는 테스트 장소',
    road_address: '서울 마포구 양화로19길 99',
    place_type: 'cafe',
    zeropay_status: 'available',
    average_rating: 3.8,
    review_count: 2,
    added_by_name: '무좌표',
    recommendation_count: 1,
    my_recommendation_active: false,
    my_review: null,
    reviews: [],
  },
  {
    id: 'place-review-fail',
    naver_place_id: '10005',
    naver_place_url: 'https://map.naver.com/p/entry/place/10005',
    name: '리뷰 저장 실패 장소',
    road_address: '서울 마포구 실패로 5',
    latitude: 37.55651,
    longitude: 126.92641,
    place_type: 'cafe',
    zeropay_status: 'available',
    average_rating: 3.9,
    review_count: 3,
    added_by_name: '오류검증',
    recommendation_count: 0,
    my_recommendation_active: false,
    my_review: null,
    reviews: [
      {
        id: 'review-6',
        author_name: '오류검증',
        content: '리뷰 저장 실패 흐름 테스트용 장소입니다.',
        created_at: '2026-03-02',
        rating_score: 4,
      },
    ],
  },
]

export const DEFAULT_SELECTED_PLACE_ID = null
